import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import Footer from "./_components/Footer";
import Features from "./_components/Features";
import CartContextProvider from "./_context/CartContextProvider";
import { getUserCart, getWishlistAction } from "./_actions/cart.actions";
import WishlistContextProvider from "./_context/WishlistContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// في ملف layout.tsx
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  
  // تجلب البيانات مع توفير "Default Object" كامل الهوية
  const userCart = (await getUserCart()) || { 
    status: "success", 
    numOfCartItems: 0, 
    data: { 
      products: [], 
      totalCartPrice: 0 
    } 
  };

  const wishlistData = (await getWishlistAction()) || { 
    status: "success", 
    count: 0, 
    data: [] 
  };

  return (
    <html lang="en">
      <body>
        <CartContextProvider userCart={userCart}>
          <WishlistContextProvider userWishlist={wishlistData}>
            <Navbar />
            <main className="pt-[70px]">{children}</main>
            <Footer />
          </WishlistContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}