import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { Toaster } from "sonner";
import Footer from "./_components/Footer";
import Features from "./_components/Features";
import CartContextProvider from "./_context/CartContextProvider";
import { getUserCart, getWishlistAction } from "./_actions/cart.actions";
import WishlistContextProvider from "./_context/WishlistContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const userCart =  await getUserCart()
// const userCart = await getUserCart() || { totalCartPrice: 0, products: [] };
const wishlistData = await getWishlistAction(); 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>
          <CartContextProvider userCart={userCart}>
<WishlistContextProvider userWishlist={wishlistData}>


          <Toaster />
        <Navbar/>
        
<main className="pt-[70px]"> 
  {children}
</main> 
</WishlistContextProvider>
</CartContextProvider>
        {/* {children} */}
        < Features />
        <Footer />
      </body>
    </html>
  );
}
